### ISSUE TITLE
Error in rowSums

### ISSUE THREAD

**Issue by vlabatut** [schochastics/signnet#1]
Hi,

I'm currently checking out your `signnet` library, thanks for your effort, it seems very nice.

However, I've got this error when trying to use the `degree_signed` function:
`Error in rowSums(P) : 'x' must be an array of at least two dimensions`

From what I understand, this is because R tries to use the generic `rowSum` when the matrices in `degree_signed` are sparse ones, of the `dgCMatrix` class. I guess the issue could be solved by explicitly calling `Matrix::rowSums` instead of just `rowSum` (or `colSums`).

Best

**Comment by schochastics** [comment]
thanks! should be fixed now

**Comment by vlabatut** [comment]
Yes, thanks!
