### ISSUE TITLE
[Suggestion] Add border around your visualization in README.md

### ISSUE THREAD

**Issue by cosimameyer** [schochastics/signnet#11]
I love your visualization and the explanation in your README.md. But since I am using dark mode in my browser, I find it hard to read your first visualization (see screenshot). This is only a suggestion, but if you had the time, it would be fantastic to add a border around the visualization to make it readable 😊

(part of https://github.com/openjournals/joss-reviews/issues/4987)

 
<img width="871" alt="image" src="https://user-images.githubusercontent.com/7782895/208484344-03a74189-83ad-4a4f-b985-e50935edf13e.png">

**Comment by schochastics** [comment]
Oh, thats bad because the text is also hidden. I added a white background now which should fix the readability issues.
fyi the figure is made with [roughnet](https://github.com/schochastics/roughnet).
