### ISSUE TITLE
Add code snippets to reproduce triad_census_signed() visualization in README.md

### ISSUE THREAD

**Issue by cosimameyer** [schochastics/signnet#12]
For beginners (or users in general), I think adding code snippets to reproduce the `triad_census_signed()` in the README.md would be a great asset (similar to the `ggblock()` examples).

The code snippets are missing here:

<img width="907" alt="image" src="https://user-images.githubusercontent.com/7782895/208923406-a63bd936-f635-4678-8868-f37f9b348bb6.png">

(This issue is part of the review https://github.com/openjournals/joss-reviews/issues/4987)

**Comment by schochastics** [comment]
The code for the `ggblock` figures is already in the README. I see that there is a bit of a confusion for the `triad_census_signed()`. That function produces the count of each of the 138 triads than can occur. The figure is just there to shows what these triads look like and cannot be reproduced with the package. I added a short description now which hopefully makes this clear.

**Comment by cosimameyer** [comment]
Sorry for the confusion here that may be caused by comment. 
I was actually looking for a code snippet to reproduce the figure similar to the one you have already provided for `ggblock()`  🙂 
For me it doesn't matter that much which package produces the figure that I added above - but as a user who goes through the README, I'd want to have code snippets that explain how you generated the figure (in case I want to replicate it). I hope this makes my suggestion clear 🙂

**Comment by schochastics** [comment]
Ok now I got it :slightly_smiling_face: .
Since the code is a bit more complicated, I put it in a gist that is linked in the README.
