### ISSUE TITLE
[Suggestion] Quality checks/Code Hygiene

### ISSUE THREAD

**Issue by cosimameyer** [schochastics/signnet#18]
When developing R packages, I usually run a couple of functions that are helpful to automatically check different dimensions of quality (spelling, linter, ...). I used the following functions and they threw a couple of warnings/errors you might want to have a look at:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/7782895/208950553-9fee3dfc-1ece-403f-9ad3-c878299fe7be.png">
 
[Source for screenshot with full list of checks](https://www.mzes.uni-mannheim.de/socialsciencedatalab/article/r-package/#section6)

The warnings included:

- Spelling errors
- Increase unit tests for code coverage
- Use `TRUE`/`FALSE` instead of `T`/`F`
- Avoid `1:length()` (error prone)
- `fix this R CMD check ERROR: Package suggested but
    not available: ‘ggraph’ The suggested packages are required
    for a complete check.`
- Typical linting errors (add spaces, avoid long code lines)
- Your DESCRIPTION does not adhere to the "tidy description" standards (if you want to follow the conventions, run `usethis::use_tidy_description()`)

(This issue is part of the review: https://github.com/openjournals/joss-reviews/issues/4987; the references above are based on the development version of your package that is currently on GitHub)

**Comment by schochastics** [comment]
fixed what I was able fix, except the code coverage (see review):
- spell check now only returns words that it is not familiar with
- All `T`/`F` where exchanged with `TRUE`/`FALSE`
- removed instances `1:length`
