### ISSUE TITLE
[Suggestion] Set package name in paper always in code block

### ISSUE THREAD

**Issue by cosimameyer** [schochastics/signnet#19]
When going through the paper, I recognized a mismatch in the fonts that were used to refer to `igraph`. Within one paragraph, the package was addressed as `igraph` and igraph (see screenshot) - and I'm not sure why. For consistency, I recommend setting package references in code blocks and referring to the package as `igraph`.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/7782895/208954841-4512a93c-a8d6-4a74-af0a-d25a568ab5c9.png">

(This issue is part of the review: https://github.com/openjournals/joss-reviews/issues/4987)

**Comment by schochastics** [comment]
Seems I forgot to put igraph between backticks on several occasions. Should be fixed now
