### ISSUE TITLE
signnet signed_triangles returns edge indices not node indices as advertised

### ISSUE THREAD

**Issue by Zygodon** [schochastics/signnet#20]
I'm using signed_triangles() to obtain a list of vertex ids, according to the specification: Value
matrix of **vertex ids** and the number of positive ties per triangle

Your example script:
library(igraph)
g <- graph.full(4)
E(g)$sign <- c(-1, 1, 1, -1, -1, 1)
signed_triangles(g)

output:
     V1 V2 V3 P
[1,]  1  5  3 1
[2,]  1  4  2 1
[3,]  2  6  3 3
[4,]  4  6  5 1

But g has only four nodes. There is no V5 or V6. But there are six edges.
What is going on here? I really want a list of the vertex ids.

Thank you for looking into this!

**Comment by schochastics** [comment]
you discovered quite the bug here, but it should be fixed now. New version is submitted to CRAN but if you install it from here, you get the fixed version already

**Comment by Zygodon** [comment]
Thank you David.

**Comment by Zygodon** [comment]
Thank you, David - that was very prompt. Let me take this opportunity to
thank you for your excellent tutorials, they have taught me a lot.

**Comment by Zygodon** [comment]
Hi David,

Sorry to bother you but I can't update to signnet 1.02, although I can see
it in your repo and RStudio tells me that the update is available. Is this
because CRAN has not released it yet? I don't really want to compile the
binaries.

Thanks,

John Pilkington

**Comment by schochastics** [comment]
usually it takes a while until it is build on CRAN for windows. I still see
`r-oldrel: signnet_1.0.1.zip` [here](https://cran.rstudio.com/web/packages/signnet/index.html) so I assume it is not updated yet. This can take a few days. I will keep an eye out too

**Comment by Zygodon** [comment]
Thanks David. There’s really no hurry, just a natural impatience.

John
