### ISSUE TITLE
Structural balance

### ISSUE THREAD

**Issue by vlabatut** [schochastics/signnet#3]
Another suggestion then: there is the _strict_ structural balance measure, that was designed for bisections, and that considers "---" triangles as imbalanced. And there is the _generalized_ structural imbalance, which considers them as balanced, as this is required to partition the graph into more than 2 clusters.

As I understand it, your function `balance_score` computes the latter measure. Maybe it would be nice (and quite easy) to let the user compute the former.

**Comment by schochastics** [comment]
Yeah this is good point. So far I just implemented some basic stuff there but I am definitely planning to extend that function. So thanks for this suggestion.

**Comment by schochastics** [comment]
this is possible with the blockmodeling approach
